/**
 * Career Path Types
 * 
 * Types for AI-powered career discovery, skill assessment, and learning plans
 */

// ============================================
// CAREER PATH CORE TYPES
// ============================================

export type CareerSource = 'ai-generated' | 'curated' | 'user-created';
export type DemandLevel = 'low' | 'medium' | 'high' | 'very-high';
export type DemandTrend = 'declining' | 'stable' | 'growing' | 'booming';
export type EntryDifficulty = 'beginner-friendly' | 'moderate' | 'challenging' | 'expert';
export type AutomationRisk = 'very-low' | 'low' | 'medium' | 'high';
export type SkillImportance = 'essential' | 'important' | 'nice-to-have';

export interface CareerPath {
    id: string;
    title: string;
    description: string;
    generatedAt: Date;
    source: CareerSource;

    // User Association (for persistence)
    userId?: string;
    savedAt?: Date;

    // Skill Graph
    skillCategories: SkillCategory[];
    totalSkillCount: number;

    // Linked Courses (generated by CareerCourseGeneratorAgent)
    courseIds: string[];

    // Market Intelligence
    market: {
        demand: DemandLevel;
        demandTrend: DemandTrend;
        salaryRange: { min: number; max: number; median: number };
        topHiringIndustries: string[];
        topLocations: string[];
        growthOutlook: string;
    };

    // Entry Requirements
    entry: {
        difficulty: EntryDifficulty;
        typicalBackground: string[];
        timeToEntry: string;
        certifications: Certification[];
    };

    // AI Impact
    aiImpact: {
        automationRisk: AutomationRisk;
        riskExplanation: string;
        futureProofSkills: string[];
        aiAugmentation: string;
    };

    // Learning Resources
    resources: {
        platformCourses: string[];
        externalResources: ExternalResource[];
        communities: CommunityLink[];
        books: BookReference[];
    };

    // Related
    relatedCareers: string[];
    transitionPaths: TransitionPath[];
}

export interface Certification {
    name: string;
    provider: string;
    url?: string;
    importance: SkillImportance;
}

export interface ExternalResource {
    title: string;
    url: string;
    type: 'article' | 'video' | 'course' | 'documentation';
    free: boolean;
}

export interface CommunityLink {
    name: string;
    platform: 'discord' | 'reddit' | 'slack' | 'linkedin' | 'other';
    url: string;
}

export interface BookReference {
    title: string;
    author: string;
    url?: string;
}

export interface TransitionPath {
    toCareer: string;
    sharedSkillsPercent: number;
    additionalSkillsNeeded: string[];
}

// ============================================
// SKILL TYPES
// ============================================

export interface SkillCategory {
    name: string;
    weight: number;
    skills: Skill[];
}

export interface Skill {
    id: string;
    name: string;
    importance: SkillImportance;
    dependencies: string[];

    // Assessment - legacy quick questions
    assessmentQuestions: SkillAssessmentQuestion[];
    // Full assessment bank ID (10-15 questions)
    assessmentBankId?: string;

    proficiencyLevels: {
        beginner: string;
        intermediate: string;
        advanced: string;
    };

    // Learning
    learningResources: {
        platformCourses: string[];
        estimatedTimeToLearn: string;
    };

    // Linked course for this skill
    linkedCourseId?: string;
}

export interface SkillAssessmentQuestion {
    id: string;
    question: string;
    options: string[];
    correctAnswer: number;
    difficulty: 'easy' | 'medium' | 'hard';
}

// ============================================
// USER CAREER PROFILE
// ============================================

export interface UserCareerProfile {
    userId: string;

    // Discovered Strengths
    discoveredStrengths: {
        skills: string[];
        traits: string[];
        assessmentDate: Date;
    };

    // Career Goals
    goals: {
        primary?: UserCareerGoal;
        alternatives: UserCareerGoal[];
    };

    // Skill State
    skills: Record<string, UserSkillState>;

    // Learning Plan
    learningPlanId?: string;
}

export interface UserCareerGoal {
    careerPathId: string;
    careerTitle: string;
    selectedAt: Date;
    targetDate?: Date;
    progress: number;
}

export interface UserSkillState {
    skillId: string;
    skillName: string;
    proficiency: number;
    sources: SkillProficiencySource[];
    lastUpdated: Date;
}

export interface SkillProficiencySource {
    type: 'assessment' | 'course-completion' | 'quiz-performance';
    value: number;
    timestamp: Date;
    reference?: string;
}

// ============================================
// PERSONALIZED LEARNING PLAN
// ============================================

export interface PersonalizedLearningPlan {
    id: string;
    userId: string;
    careerPathId: string;
    careerTitle: string;

    createdAt: Date;
    lastAdaptedAt: Date;

    currentPhaseIndex: number;
    overallProgress: number;

    estimatedCompletion: Date;

    phases: LearningPhase[];
    adaptationHistory: PlanAdaptation[];
}

export interface LearningPhase {
    order: number;
    title: string;
    description: string;
    estimatedDuration: string;

    targetSkills: {
        skillId: string;
        skillName: string;
        targetProficiency: number;
    }[];

    // Linked course IDs for this phase
    courseIds: string[];

    recommendedCourses: string[];
    externalResources: ExternalResource[];

    milestones: Milestone[];

    status: 'locked' | 'active' | 'completed';
    progress: number;
}

export interface Milestone {
    id: string;
    title: string;
    type: 'course' | 'quiz' | 'project' | 'skill-level';
    requirement: string;
    completed: boolean;
}

export interface PlanAdaptation {
    timestamp: Date;
    reason: string;
    changes: string[];
}

// ============================================
// CAREER COMPARISON
// ============================================

export interface CareerComparison {
    careers: CareerPath[];
    userId: string;
    comparison: CareerComparisonDimension[];
}

export interface CareerComparisonDimension {
    dimension: string;
    label: string;
    values: { careerId: string; value: string | number; formatted: string }[];
}

// ============================================
// CAREER DISCOVERY CHAT
// ============================================

export interface CareerDiscoveryMessage {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    timestamp: Date;
    suggestions?: CareerSuggestion[];
}

export interface CareerSuggestion {
    careerTitle: string;
    matchScore: number;
    matchReason: string;
}

// ============================================
// GENERATION TYPES
// ============================================

export type CareerGenerationStep =
    | 'researching'
    | 'analyzing-skills'
    | 'market-research'
    | 'building-path'
    | 'complete'
    | 'error';

export interface CareerGenerationProgress {
    step: CareerGenerationStep;
    message: string;
    percentage: number;
}

export interface CareerGenerationEvent {
    type: 'progress' | 'complete' | 'error';
    step?: CareerGenerationStep;
    message?: string;
    percentage?: number;
    data?: Partial<CareerPath>;
    error?: string;
}
