'use client';

import React from 'react';
import { Resource } from '@/types/resources';

interface AIArticleViewerProps {
    resource: Resource;
    onClose: () => void;
}

export default function AIArticleViewer({ resource, onClose }: AIArticleViewerProps) {
    if (resource.type !== 'ai-article') return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm overflow-y-auto">
            <div className="bg-[#0b0f12] w-full max-w-4xl min-h-[50vh] max-h-[90vh] rounded-2xl border border-white/10 shadow-2xl flex flex-col my-8">

                {/* Header */}
                <div className="px-8 py-6 border-b border-white/10 flex items-start justify-between bg-[#0b0f12] sticky top-0 z-10 rounded-t-2xl">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <span className="px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-400 text-xs font-medium border border-purple-500/20">
                                AI Article
                            </span>
                            <span className="px-2 py-0.5 rounded-full bg-white/5 text-white/60 text-xs font-medium border border-white/10">
                                {resource.duration || '5 min read'}
                            </span>
                        </div>
                        <h2 className="text-2xl font-bold text-white">{resource.title}</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-white/5 rounded-lg text-white/50 hover:text-white transition-colors"
                    >
                        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto px-8 py-8">
                    <div className="prose prose-invert max-w-none prose-headings:text-white prose-p:text-white/80 prose-li:text-white/80 prose-strong:text-white prose-code:text-[#0ea5e9]">
                        {/* 
              In a real app, use a Markdown renderer like react-markdown. 
              For now, simple rendering or ensuring content is just text.
              If content is raw HTML, use dangeriouslySetInnerHtml but be careful.
              Mocking markdown rendering for now with whitespace preservation.
            */}
                        <div className="whitespace-pre-wrap font-sans text-base leading-relaxed">
                            {resource.content || resource.description}
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className="px-8 py-4 border-t border-white/10 bg-[#13171c] rounded-b-2xl flex items-center justify-between">
                    <div className="text-xs text-white/40">
                        Generated by CBC AI Tutor • Correctness checked by AI
                    </div>
                    <div className="flex gap-3">
                        <button className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-sm text-white font-medium transition-colors">
                            Save for later
                        </button>
                        <button className="px-4 py-2 rounded-lg bg-[#0ea5e9]/10 hover:bg-[#0ea5e9]/20 text-sm text-[#0ea5e9] font-medium transition-colors">
                            Take Quiz
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
